### ISSUE TITLE
延长爬虫时间没有用

### ISSUE THREAD

**Issue by passermyh** [Lan-ce-lot/pythorch-text-classification#5]
已经把sleep时间加到20了还是只能爬两三百条

**Comment by Lan-ce-lot** [comment]
确实存在这个问题，我修改一下代码。
猜测是豆瓣评论还在加载导致漏掉了一些评论，因为他的预加载机制，页面好了但是评论还没有加载出来
解决方法：
* 爬接口而不是直接爬页面

例如https://movie.douban.com/subject/26613692/comments?start=200&limit=20&status=P&sort=new_score&comments_only=1

BTW，感谢指出问题

**Comment by Lan-ce-lot** [comment]
> 已经把sleep时间加到20了还是只能爬两三百条

已更新
https://github.com/Lan-ce-lot/pythorch-text-classification/commit/9dfcdf6448c5e6d588308313936c4450d2381a25
